### ISSUE TITLE
Filename with colon causes choking

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [ihsoft/KSPDev#10]
Hey ihsoft, I'm working on making some offline backups of KSP wikis that I often reference or expect to reference (since Internet access is sometimes a little flaky where I live), but one of your wiki pages (https://github.com/ihsoft/KSPDev/wiki/ReleaseBuilder:-Schema-1.0) has a colon in it, which causes Windows to choke on it while cloning.  Can you please change that?

**Comment by ihsoft** [comment]
I'll take a look if it can be done in an easy way. Didn't find a solution via GitHub UI, it only allows changing page title.

**Comment by Kerbas-ad-astra** [comment]
That might be enough, if changing the page title changes the 'internal' filename.

**Comment by ihsoft** [comment]
I'd rather avoid doing it. Using colon in the page title makes perfect sense. And it's not the only special symbol that may appear there. E.g. there are `/`, `"`, `?`, etc. GitHub replaces some with dashes but some are left unchanged (e.g. `:` and `"`). That said, the approach should be focused on fixing the file name instad of making page header "compatible" with the filesystem naming conventions.

**Comment by Kerbas-ad-astra** [comment]
But the title makes equally perfect sense without the colon ("ReleaseBuilder Schema 1.0"), and it means the wiki is compatible and exportable across 100% of all computer operating systems.  The MKS wiki had the same trouble, and renaming the page titles fixed it just fine.

**Comment by Kerbas-ad-astra** [comment]
Thanks!
